# Generated by Django 2.2.5 on 2020-01-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetentities',
            old_name='namedEntities',
            new_name='namedEntity',
        ),
    ]
