# Generated by Django 3.0.2 on 2020-01-25 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterops', '0002_auto_20200123_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='tweetentities',
            name='namedEntity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='twitterops.Entity'),
        ),
    ]
